services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: usersdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  next-app:
    build: .
    container_name: next-crud-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development

volumes:
  mysql-data: